### ISSUE TITLE
Code issue

### ISSUE THREAD

**Issue by mingyao1120** [fmu2/snag_release#2]
Hello, thank you for such an excellent open source work. However, when I wanted to add some components based on your code, I reported the following error 

assert len(param_dict.keys() - union_params) == 0, (
AssertionError: parameters were not separated into either decay/no decay set, 

how to solve it? Looking forward to your reply as soon as possible

**Comment by fmu2** [comment]
https://github.com/fmu2/snag_release/blob/6a21297ac7d5f8f34a2272abaa47073f6ec6ce42/libs/modeling/optim.py#L18

You need to add your custom module here.

**Comment by fmu2** [comment]
Closed
